from datetime import datetime


def generate_report_header(analysis: dict) -> str:
    return f"""
# 🔬 AI Coroner — Autopsy Report
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Project:** ai-coroner-demo (ShopBot Customer Support)

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Interactions | {analysis['total_interactions']} |
| Total Failures | {analysis['total_failures']} |
| Failure Rate | {analysis['failure_rate']}% |
| Failure Clusters | {len(analysis['clusters'])} |

---
"""


def generate_cluster_section(cluster: dict, rank: int) -> str:
    pattern = cluster["pattern"]
    examples_text = ""

    for i, ex in enumerate(cluster["examples"], 1):
        examples_text += f"""
**Example {i}:**
- 🧑 User: `{ex['input']}`
- 🤖 Bot: `{ex['output'][:120]}...`
"""

    return f"""
## 🚨 Failure #{rank}: {pattern['name']}

**Occurrences:** {cluster['count']}
**Diagnosis:** {pattern['description']}

### Examples
{examples_text}

### 💊 Prescribed Fix
{cluster['fix']}

---
"""


def generate_report_footer(analysis: dict) -> str:
    health = "🟢 Healthy" if analysis['failure_rate'] < 20 else \
        "🟡 Needs Attention" if analysis['failure_rate'] < 50 else \
            "🔴 Critical"

    return f"""
## 🏥 Overall Health: {health}

{"✅ System is performing well. Monitor for regressions." if analysis['failure_rate'] < 20 else "⚠️ Significant failure patterns detected. Apply prescribed fixes and re-evaluate." if analysis['failure_rate'] < 50 else "🚨 Critical failure rate. Immediate intervention required."}

*Report generated by The AI Coroner — autonomous LLM diagnostic agent*
"""